num = input("Digite algo no teclado: ")
print("O tipo primitivo desse valor é ", type(num))
print("Só tem espaços ?", num.isspace())
print("É um número? ", num.isnumeric())
print("É alfabético? ", num.isalpha())
print("È alfanumérico? ", num.isalnum())
print("Está em maiúsculas? ", num.isupper())
print("Está em minúsculas? ", num.islower())
print("Está capitalizada? ", num.istitle())

